#!/bin/sh

set -e

if [ "$1" = "abort-upgrade" ]; then
    # If we abort-upgrade from a version less than '41',
    # re-add dmenu alternatives
    if dpkg --compare-versions "$2" lt "41"; then
        update-alternatives --quiet --install /usr/bin/dmenu dmenu \
            /usr/bin/dmenu.default 100
        update-alternatives --quiet --install /usr/bin/dmenu dmenu \
            /usr/bin/dmenu.xft 50
    fi
fi



exit 0
